logging:
  level:
    root: INFO
    liquibase: TRACE
    org.springframework.boot.autoconfigure.liquibase: TRACE

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb   # или H2, если тесты
    driver-class-name: org.postgresql.Driver
    username: postgresql
    password: postgresql

  # ваш R2DBC
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/testdb
    username: postgresql
    password: postgresql

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

file-info:
  remote:
    base-url: https://localhost:8080
    upload-path: /upload

